version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
  mariadb:
    container_name: dev_db
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: qwerty
      MARIADB_DATABASE: wp_my_database
      MARIADB_USER: wp
      MARIADB_PASSWORD: qwerty
    ports:
      - '9906:3306'
